### PR TITLE
- fix OnServerEndCall 

### PR DESCRIPTION
**Pull request by woDeee**
- function "IsApplicableCall" wasnt found
- fix IsApplicableCall function (two times the same parameter)

### CODE REVIEW

**Comment by LorianAtashi01** [comment]
Gonna do a review today test it out and merge it if everything is okay.

**Comment by Phill030** [comment]
approved by lucifer, thanks for waiting because he moved from one country to another and hadn't the opportunity until now to test everything

**Comment by LorianAtashi01** [comment]
Thank you @Phill030 for closing and reopening this multiple times 😂😂😂😂😂♥️

**Comment by woDeee** [comment]
No problem. I'm glad to have helped. Have a nice day and thanks for the merge :)

**Pull request merged**
